// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvnpcqisowlqvdumkczc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2bnBjcWlzb3dscXZkdW1rY3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjQxNDEsImV4cCI6MjA2MDkwMDE0MX0.bCSNYdgKuoEvlmDoVZCoy1nRkAY2Hkn7zBExRyl9vMg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);